name = "cloudflare-error-page"
compatibility_date = "2024-01-01"

[build]
command = "cd react-app && npm install && npm run build"
cwd = ""

[build.upload]
format = "directory"
dir = "react-app/dist"

[[pages_build_output_dir]]
value = "react-app/dist"
